Ass03Solution/eStore/Controllers/MembersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using static eStore.Models.DBHelper;
using Ass3.Library;
using eStore.Models;

namespace eStore.Controllers
{
    public class MembersController : Controller
    {
        private IMemberRepository MemberRepository = null;

        // GET: MembersController
        public ActionResult Index()
        {
            MemberRepository = new MemberRepository();

            var memberList = MemberRepository.GetMembers();
            return View(memberList);
        }

        // GET: MembersController/Details/5
        public ActionResult Details(int id)
        {
            MemberRepository = new MemberRepository();

            var member = MemberRepository.GetMemberByID(id);
            if (member == null)
            {
                return NotFound();
            } 
            return View(member);
        }

        // GET: MembersController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MembersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Member member)
        {
            try
            {
                MemberRepository = new MemberRepository();
                if (ModelState.IsValid)
                {
                    MemberRepository.InsertMember(member);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }

        // GET: MembersController/Edit/5
        public ActionResult Edit(int id)
        {
            MemberRepository = new MemberRepository();
            var member = MemberRepository.GetMemberByID(id);
            return View(member);
        }

        // POST: MembersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Member member)
        {
            MemberRepository = new MemberRepository();
            
            try
            {
                if (ModelState.IsValid)
                {
                    MemberRepository.UpdateMember(member);
                }
                if (member.IsAdmin)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View(member);
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }

        // GET: MembersController/Delete/5
        public ActionResult Delete(int id)
        {
            MemberRepository = new MemberRepository();
            var member = MemberRepository.GetMemberByID(id);
            return View(member);
        }

        // POST: MembersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            MemberRepository = new MemberRepository();
            try
            {
                MemberRepository.DeleteMember(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Ass03Solution/eStore/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Ass3.Library;
using Microsoft.AspNetCore.Mvc.Rendering;
using eStore.Models;

namespace eStore.Controllers
{
    public class OrdersController : Controller
    {
        private OrderRepository OrderRepository = null;

        // GET: OrdersController
        public ActionResult Index(int? userID)
        {
            OrderRepository = new OrderRepository();
            if (userID == null)
            {
                var orders = OrderRepository.GetOrders();
                return View(orders);
            }
            else
            {
                var orders = OrderRepository.GetOrders(userID.Value);
                return View(orders);
            }
            
        }

        // GET: OrdersController/Details/5
        public ActionResult Details(int id)
        {
            OrderRepository = new OrderRepository();
            var order = OrderRepository.GetOrderByID(id);
            return View(order);
        }

        // GET: OrdersController/Create
        public ActionResult Create()
        {
            ViewBag.MemberId = GetMemberList();
            return View();
        }

        // POST: OrdersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserOrderViewModel orderViewModel)
        {
            OrderRepository = new OrderRepository();
            
            try
            {
                if (ModelState.IsValid)
                {
                    UserOrder userOrder = orderViewModel.ToDBModel();
                    if(userOrder.Freight > 0)
                    {
                        OrderRepository.InsertOrder(userOrder);
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Input must > 0";
                        return RedirectToAction(nameof(Create));
                    }
                } 
                else
                {
                    throw new Exception("Error");
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(orderViewModel);
            }
        }

        // GET: OrdersController/Edit/5
        public ActionResult Edit(int id)
        {
            OrderRepository = new OrderRepository();
            ViewBag.MemberId = GetMemberList();
            var userOrder = OrderRepository.GetOrderByID(id);
            return View(new UserOrderViewModel(userOrder));
        }

        // POST: OrdersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, UserOrderViewModel orderViewModel)
        {
            OrderRepository = new OrderRepository();

            try
            {
                if (ModelState.IsValid)
                {
                    UserOrder userOrder = orderViewModel.ToDBModel();
                    if(userOrder.Freight > 0)
                    {
                        OrderRepository.UpdateOrder(userOrder);
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Input must > 0";
                        return RedirectToAction(nameof(Edit));
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(orderViewModel);
            }
        }

        // GET: OrdersController/Delete/5
        public ActionResult Delete(int id)
        {
            OrderRepository = new OrderRepository();
            var userOrder = OrderRepository.GetOrderByID(id);
            return View(userOrder);
        }

        // POST: OrdersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, UserOrder userOrder)
        {
            OrderRepository = new OrderRepository();
            try
            {
                OrderRepository.DeleteOrder(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        private List<SelectListItem> GetMemberList()
        {
            MemberRepository memberRepository = new MemberRepository();
            var members = memberRepository.GetMembers();
            var memberIdList = new List<SelectListItem>();

            foreach (var member in members)
            {
                memberIdList.Add(new SelectListItem()
                {
                    Text = member.MemberId.ToString() + ". " + member.Email,
                    Value = member.MemberId.ToString()
                });
            }

            return memberIdList;
        }
    }
}

Ass03Solution/eStore/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using static eStore.Models.DBHelper;
using Ass3.Library;

namespace eStore.Controllers
{
    public class ProductsController : Controller
    {
        private IProductRepository ProductRepository = null;

        // GET: ProductsController
        public ActionResult Index(string productName = "",
            int lowerPrice = 0, int upperPrice = 0)
        {
            ProductRepository = new ProductRepository();
            IEnumerable<Product> productList = null;

            if (string.IsNullOrEmpty(productName) && lowerPrice == 0 
                && upperPrice == 0)
            {
                productList = ProductRepository.GetProductList();
            }
            else
            {
                productList = ProductRepository
                    .SearchProducts(productName, lowerPrice, upperPrice);
                ViewBag.productName = productName;
                ViewBag.lowerPrice = lowerPrice;
                ViewBag.upperPrice = upperPrice;
            }
            
            return View(productList);
        }

        // GET: ProductsController/Details/5
        public ActionResult Details(int id)
        {
            ProductRepository = new ProductRepository();
            var product = ProductRepository.GetProductByID(id);
            return View(product);
        }

        // GET: ProductsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product)
        {
            try
            {
                ProductRepository = new ProductRepository();
                if (ModelState.IsValid)
                {
                    if(product.Category <= 0) { TempData["ErrorMessageCat"] = "Category must > 0"; }
                    if(product.UnitPrice <= 0) { TempData["ErrorMessagepPrice"] = "Price must > 0"; }
                    if(product.UnitsInStock <= 0) { TempData["ErrorMessageStock"] = "Units must > 0"; }
                    if(product.Category <= 0 || product.UnitPrice <= 0 || product.UnitsInStock <= 0)
                    {
                        return RedirectToAction(nameof(Create));
                    }

                    ProductRepository.AddProduct(product);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }

        // GET: ProductsController/Edit/5
        public ActionResult Edit(int id)
        {
            ProductRepository = new ProductRepository();
            var product = ProductRepository.GetProductByID(id);
            return View(product);
        }

        // POST: ProductsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Product product)
        {
            ProductRepository = new ProductRepository();
            try
            {
                if (ModelState.IsValid)
                {
                    if (product.Category <= 0) { TempData["ErrorMessageCat"] = "Category must > 0"; }
                    if (product.UnitPrice <= 0) { TempData["ErrorMessagepPrice"] = "Price must > 0"; }
                    if (product.UnitsInStock <= 0) { TempData["ErrorMessageStock"] = "Units must > 0"; }
                    if (product.Category <= 0 || product.UnitPrice <= 0 || product.UnitsInStock <= 0)
                    {
                        return RedirectToAction(nameof(Edit));
                    }

                    ProductRepository.UpdateProduct(product);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(product);
            }
        }

        // GET: ProductsController/Delete/5
        public ActionResult Delete(int id)
        {
            ProductRepository = new ProductRepository();
            var product = ProductRepository.GetProductByID(id);
            return View(product);
        }

        // POST: ProductsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            ProductRepository = new ProductRepository();
            try
            {
                ProductRepository.DeleteProduct(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

    }
}

Ass03Solution/eStore/Controllers/ReportsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using static eStore.Models.DBHelper;
using Ass3.Library;

namespace eStore.Controllers
{
    public class ReportsController : Controller
    {
        private IOrderDetailRepository OrderDetailRepository = null;

        // GET: ReportsController
        public ActionResult Index(string Generate, DateTime startDate , DateTime endDate)
        {
            OrderDetailRepository = new OrderDetailRepository();
            List<Report> report = null;
            if(Generate == null)
            {
                report = OrderDetailRepository.GetAll();
            }
            else
            {
                report = OrderDetailRepository.GetSaleReport(startDate, endDate);
                ViewBag.startDate = startDate;
                ViewBag.endDate = endDate;
            }
            return View(report);
        }

    }
}

Ass03Solution/eStore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using eStore.Models;
@using Ass3.Library;

@inject IHttpContextAccessor HttpContextAccessor

@{
    ISession session = HttpContextAccessor.HttpContext.Session;
    Member member = session.GetObject<Member>("MEMBER");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/eStore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">eStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (@member.IsAdmin)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Members" asp-action="Index">Member</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index"
                               asp-route-userID=@session.GetInt32("USER_ID")>Order</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reports" asp-action="Index">Reports</a>
                            </li>
                        }
                        @if (!member.IsAdmin)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Members" asp-action="Edit"
                                asp-route-id=@member.MemberId>Member</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index"
                                asp-route-userID=@member.MemberId>Order</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - eStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>